### ISSUE TITLE
Cannot build demos on Linux

### ISSUE THREAD

**Issue by ghost** [NVlabs/moderngpu#2]
make: *** No rule to make target `demo.o', needed by `demo'.  Stop.

pez@pezmachine:~/Development/quantcrunch/demo$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu

**Comment by sdalton1** [comment]
Build successful on Ubuntu 14.04 with CUDA 7.0.
