### ISSUE TITLE
Argument swap in ReduceByKey() in demos.cu

### ISSUE THREAD

**Issue by shridharama** [NVlabs/moderngpu#7]
Hi, 
In the DemoReduceByKey method in demos.cu, 2 of the arguments given to the ReduceByKey method are mixed up:

ReduceByKey(keysDevice->get(), valsDevice->get(), count, 0, mgpu::plus<int>(), mgpu::equal_to<int>(), **destDevice->get(), keysDestDevice->get()**, &numSegments, (int*)0, context);

should be

ReduceByKey(keysDevice->get(), valsDevice->get(), count,	0, mgpu::plus<int>(), mgpu::equal_to<int>(), **keysDestDevice->get(),  destDevice->get()**, &numSegments, (int*)0, context);

in order for the output to be printed correctly.

This should aso be fixed in the documentation - https://nvlabs.github.io/moderngpu/segreduce.html

Thanks!

**Comment by seanbaxter** [comment]
moderngpu 1.0 is obsolete. should build with 2.0.
